### ISSUE TITLE
Design System

### ISSUE THREAD

**Issue by danicuki** [w3b3d3v/kyodo-protocol#11]

**Comment by mikaelcarrara** [comment]
A first version...

![Image](https://github.com/w3b3d3v/kyodo-protocol/assets/22267/dcae6215-1f61-4ab7-a503-9824cbdcaa3f)

**Comment by danicuki** [comment]
Can we have a public link to the design system and everything open sourced?

**Comment by mikaelcarrara** [comment]
This is not just the design system but all kyodo designs (branding, UI, website, etc...)

https://www.figma.com/file/F4ZdyaBpDjFw8l21IsTmIO/Ky%C5%8Dd%C5%8D-Protocol?type=design&node-id=6%3A4&mode=design&t=wXKLJihrczCxRd4i-1

**Comment by danicuki** [comment]
Please post a README.md file in the kyodo-protocol-assets linking to this Figma, and explaining all other assets in the repo. 
Remember, this is an open source project, everything will be publicly advertised and available for community members contribution

**Comment by mikaelcarrara** [comment]
I already did that, I'll check it out...
