### ISSUE TITLE
Batch payment of multiple agreements

### ISSUE THREAD

**Issue by piadascripto** [w3b3d3v/kyodo-protocol#184]
**Description:**  Pay several agreements at once. User choose chain after selecting all agreements he/she wants to pay. Metamask is called to approve all payments at once. 

**Acceptance Criteria:** Payment is successfully made after completing the flow 

**Requirements:** Backend and smart contracts interactions 

**Context:** User making the payments of agreements he/she chose

**Comment by nomadbitcoin** [comment]
In the first version of this feature, payment for all agreements will be made on the same token and the user must have the total amount available as a balance.

In a future version, we could have a selection of tokens for each agreement, but we will need to generate approval transactions for each of these tokens.
