### ISSUE TITLE
add VaulToken after Redeem

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/kyodo-protocol#28]
Show a button to add the vaultToken at metamask token list after the transaction to Redeem is processed

**Comment by danicuki** [comment]
I think "community token" would be a better name than vaultToken. From the user perspective, it doesn't matter if it is a vault. I am getting confused on the interface. As a user, I just want to know how much I have "locked", on both community token and stable USD tokens.

**Comment by nomadbitcoin** [comment]
CommunityTokens are the incentive tokens and are not being distributed yet. You are seeing the vaultTokens because we are using it for testing to show some balance on the screen, but in practice, the vaultTokens only represent the amount you have deposited to be redeemed.

**Comment by danicuki** [comment]
The only thing that is redeemable are community tokens and stable coin tokens. This is what the user should see on screen. The user doesnt have to know how this is implemented, or even see if it is a Vault or whatever.

**Comment by nomadbitcoin** [comment]
I said exactly that. Vault Token is appearing only because during the tests it is the token used to show some balance, I will remove it and use only the stablecoins.
