### ISSUE TITLE
Implement the final design - Front

### ISSUE THREAD

**Issue by danicuki** [w3b3d3v/kyodo-protocol#32]
**Structure**

- [x] Main navigation (menu)
- [x] Footer with terms and privacy nav
- [x] Mobile general adjustments

**Visual enhancement**

- [x] ConnectWallet page
- [x] AddAgreement page
- [x] AgreementList page

**Comment by mikaelcarrara** [comment]
closes #36

**Comment by mikaelcarrara** [comment]
closes #57

**Comment by mikaelcarrara** [comment]
closes #61
