### ISSUE TITLE
Solana - create agreement

### ISSUE THREAD

**Issue by danicuki** [w3b3d3v/kyodo-protocol#41]

**Comment by Jaxiii** [comment]
Is this a Solana version of [Pay agreement#9](https://github.com/w3b3d3v/kyodo-protocol/issues/9)?
I can start drafting something.

**Comment by danicuki** [comment]
The original issue for create agreement was not created in github. But it already exists in the code. 
Now, for Solana, we separated into different issues: 
- #45
- #41
- #43

**Comment by Jaxiii** [comment]
Since merge was accepted, Im closing this issue.
